[sources.suricata]
type = "file"
include = ["/var/log/suricata/eve.json"]

[transforms.parse_suricata]
type = "remap"
inputs = ["suricata"]
source = '''
. = parse_json!(string!(.message))
'''

[sinks.prometheus_exporter_suricata]
type = "prometheus_exporter"
inputs = ["parse_suricata"]
address = "0.0.0.0:9598"
when_full = "block"
