soc_admin:
  cluster_permissions:
    - "cluster_all"
  index_permissions:
    - index_patterns:
        - "*"
      allowed_actions:
        - "indices_all"

vector_writer:
  cluster_permissions:
    - "cluster_all"
  index_permissions:
    - index_patterns:
        - "*"
      allowed_actions:
        - "crud"
        - "create_index"

api_reader:
  index_permissions:
    - index_patterns:
        - "*"
      allowed_actions:
        - "read"
        - "search"
